name: Release
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  compile:
    name: Compile the project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo Latest
        uses: actions/checkout@v2
      - name: Get Deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.x
      - run: mkdir -p dist
      - name: Compile with Deno
        run: ./compile
      - name: Create Github Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/bglcares
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Run latest-tag
        uses: EndBug/latest-tag@latest
